## Correlation
Correlation is the raelationships between two or more variables (or features) of a dataset.<br>
Each datapoint in the dataset is an **observation** and the **features** are the properties or attributes of those observations

##### Forms of correlation

1. **Negative correlation** <br>
A relationship between two variables in which one variable increase as the other decreases and vice versa.<br>
A perfect negative correlation is represented by the value -1.0 <br><br>

2. **No/ Zero correlation** <br>
There is no relationship between the two variables.<br> As one variable moves in one way, the other moves in an unrelated direction.<br><br>

3. **Positive correlation** <br>
A relationship between two variables that move in tandem - in the same direction. When one variable decreases, the other variable decreases, or one variable increases while the other increases. <br><br><br>


**NB. Correlation does not indicate causation.** It quantifies the strength of the relationship between the features of a dataset. 




#### Statistics to quantify correlation
*Pearson's coefficient.*<br>
It measures linear correlation. <br>

*Spearman & Kendall coefficient* <br>
Compare the ranks of data


### Numpy Correlation Calculation

In [8]:
import numpy as np
x = np.arange (10,20) # create an array of integers between 10 (inclusive) and 20 (exclusive)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

array([ 2,  1,  4,  5,  8, 12, 18, 25, 96, 48])

In [11]:
#Correlation Matrix
#NB. Ensure that the two arrays are of the same length.
r = np.corrcoef (x, y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

In [12]:
#correlation coefficient of x
r[0,1]

0.7586402890911867

In [13]:
#correlation coefficient of y
r[1,0]

0.7586402890911869

The correlation coeffcients of x and y are equal. This represents the **Pearson correlation coefficient** for x and y. In this case approc=ximately 0.76

### Scipy Correlation Calculation

In [18]:
import scipy.stats
scipy.stats.pearsonr(x,y) # Pearson's r

PearsonRResult(statistic=0.758640289091187, pvalue=0.010964341301680815)

In [19]:
scipy.stats.spearmanr(x,y) # Spearman's rho

SignificanceResult(statistic=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [20]:
scipy.stats.kendalltau(x, y)  # Kendall's tau

SignificanceResult(statistic=0.911111111111111, pvalue=2.9761904761904762e-05)

There functions return objects that contain two values:<br>
1. The correlation coefficient.<br>
2. The p-value <br><br>

You use the p-value in statistical methods when you’re testing a hypothesis. The p-value is an important measure that requires in-depth knowledge of probability and statistics to interpret.<br><br>


#### Heatmaps 

In [5]:
import matplotlib.pyplot as mp
import seaborn as sns

#import file with data
import pandas as pd
data = pd.read_csv('Data/exams.csv')

'''
prints data that will be plotted
The columns shown here are selected by corr() since they are ideal for the plot

'''

print(data.corr(numeric_only = True))

# plotting correlation heatmap
dataplot = sns.heatmap(data.corr(numeric_only = True), cmap="YlGnBu", annot=True)
  
# displaying heatmap
mp.show()

               math score  reading score  writing score
math score       1.000000       0.819398       0.805944
reading score    0.819398       1.000000       0.954274
writing score    0.805944       0.954274       1.000000
